name: Deploy to VPS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '20'

    - name: Checkout repo
      uses: actions/checkout@v2

    - name: Set up SSH
      uses: webfactory/ssh-agent@v0.4.1
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

    - name: Deploy to VPS
      run: |
        ssh zentala@164.68.104.13 'rm -rf /home/zentala/www/agency.zentala && mkdir -p /home/zentala/www/agency.zentala'
        scp -r . zentala@164.68.104.13:/home/zentala/www/agency.zentala
        ssh zentala@164.68.104.13 'cd /home/zentala/www/agency.zentala && npm install && npm run build && pm2 restart zentala.agency'
